#!/usr/bin/env python3
"""Recovery scenario 1: a single slide fails generation.

slide_01 success, slide_02 success, slide_03 ``IMAGE_GENERATION_FAILED``.

Contract under test:

* the two finished slides stay finished and are never re-generated
* the failed slide lands in ``generation_failed`` with its error code preserved
* slides after the failure are never optimistically marked complete
* AGY (and only AGY) may move ``generation_failed -> ready``
* the retry is generation 2 / attempt 2, and attempt 1 is still in history
* the untouched slides keep generation 1

Run with::

    python3 -m unittest discover -s skills/agy-ppt/tests -t skills/agy-ppt/tests -p "test_*.py"
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parents[1]
if str(TESTS_DIR) not in sys.path:
    sys.path.insert(0, str(TESTS_DIR))

from helpers.fault_matrix import attach_matrix_tests  # noqa: E402
from helpers.fake_image_worker import (  # noqa: E402
    FAULT_GENERATION_FAILED,
    FAULT_TIMEOUT,
)
from helpers.recovery_deck import (  # noqa: E402
    SLIDE_GENERATED,
    SLIDE_GENERATION_FAILED,
    SLIDE_PLANNED,
    SLIDE_READY,
    RecoveryTestCase,
    plan_dispatch,
)
from project_state import InvalidStateTransition  # noqa: E402


class GenerationFailureTests(RecoveryTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.advance_to_slide_generation()
        # slide_03 fails the first time, then succeeds.
        self.worker.set_plan(
            "slide_03", fault=FAULT_GENERATION_FAILED, succeed_on=2
        )
        self.first_pass = [self.dispatch(sid) for sid in ("slide_01", "slide_02", "slide_03")]

    # -- immediate aftermath ----------------------------------------------
    def test_completed_slides_stay_completed(self):
        for slide_id in ("slide_01", "slide_02"):
            self.assert_slide(slide_id, SLIDE_GENERATED, generation=1, attempts=1)
            self.assert_valid_final_image(slide_id)

    def test_failed_slide_is_generation_failed_with_error_code(self):
        slide = self.assert_slide("slide_03", SLIDE_GENERATION_FAILED, generation=1, attempts=1)
        self.assertEqual(slide["attempts"][0]["error_code"], FAULT_GENERATION_FAILED)
        self.assertEqual((slide["blocker"] or {}).get("error_code"), FAULT_GENERATION_FAILED)
        self.assert_not_generated("slide_03")

    def test_later_slides_are_not_marked_complete(self):
        slide = self.assert_slide("slide_04", SLIDE_PLANNED, generation=0, attempts=0)
        self.assertIsNone(slide["image_path"])

    def test_failure_does_not_advance_phase(self):
        self.assertEqual(self.state.phase, "slide_generation")

    def test_state_survives_reload(self):
        self.reload()
        self.assert_slide("slide_01", SLIDE_GENERATED, generation=1)
        self.assert_slide("slide_03", SLIDE_GENERATION_FAILED, generation=1, attempts=1)
        self.assert_slide("slide_04", SLIDE_PLANNED, generation=0)

    def test_resume_plan_skips_settled_slides(self):
        self.reload()
        self.assertEqual(plan_dispatch(self.state), ["slide_03", "slide_04"])

    def test_generation_failed_cannot_jump_straight_to_generated(self):
        with self.assertRaises(InvalidStateTransition):
            self.state.set_slide_status("slide_03", SLIDE_GENERATED)

    # -- the retry ---------------------------------------------------------
    def test_agy_retry_reaches_generated_on_second_attempt(self):
        before = self.snapshot(["slide_01", "slide_02"])
        self.retry("slide_03")
        self.assert_slide("slide_03", SLIDE_READY, generation=1)

        outcome = self.dispatch("slide_03")
        self.assertEqual(outcome.status, "completed")
        self.assertEqual(outcome.generation, 2)

        slide = self.assert_slide("slide_03", SLIDE_GENERATED, generation=2, attempts=2)
        self.assertEqual([a["generation"] for a in slide["attempts"]], [1, 2])
        self.assertEqual(slide["attempts"][0]["status"], "error")
        self.assertEqual(slide["attempts"][1]["status"], "completed")
        self.assert_valid_final_image("slide_03")

        # Untouched slides must not have been re-generated by the retry.
        self.assert_untouched(["slide_01", "slide_02"], before)
        self.assertEqual(len(self.worker.calls_for("slide_01")), 1)
        self.assertEqual(len(self.worker.calls_for("slide_02")), 1)
        self.assertEqual(len(self.worker.calls_for("slide_03")), 2)

    def test_retry_preserves_attempt_one_history_after_reload(self):
        self.retry("slide_03")
        self.dispatch("slide_03")
        self.reload()
        attempts = self.state.slide("slide_03")["attempts"]
        self.assertEqual(len(attempts), 2)
        self.assertEqual(attempts[0]["error_code"], FAULT_GENERATION_FAILED)
        self.assertNotEqual(attempts[0]["idempotency_key"], attempts[1]["idempotency_key"])


class GenerationFailureMatrixTests(RecoveryTestCase):
    """Table-driven rows whose expected outcome is ``generation_failed``."""


attach_matrix_tests(GenerationFailureMatrixTests, (FAULT_GENERATION_FAILED, FAULT_TIMEOUT))


if __name__ == "__main__":
    unittest.main()
