#!/usr/bin/env python3
"""Shared harness for the Phase 9 deterministic recovery suite.

:class:`RecoveryTestCase` gives every recovery scenario the same deterministic
starting point:

* a throwaway workspace under ``tempfile``
* a real :class:`project_state.ProjectState` (the frozen production control
  plane -- exercised, never modified) advanced to ``slide_generation``
* a :class:`helpers.fake_image_worker.FakeImageWorker`
* a hard guard that fails the test if anything tries to spawn a process, so no
  scenario can silently reach the real Codex CLI or burn subscription quota

The harness models AGY, not the workers: it dispatches, records results, and
performs the AGY-only visual-QA judgements. All decisions are explicit; nothing
here guesses a slide outcome or auto-advances a phase.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable
from unittest import mock

TESTS_DIR = Path(__file__).resolve().parents[1]
SKILL_DIR = TESTS_DIR.parent
SCRIPTS_DIR = SKILL_DIR / "scripts"
for _path in (str(TESTS_DIR), str(SCRIPTS_DIR)):
    if _path not in sys.path:
        sys.path.insert(0, _path)

import project_state as ps  # noqa: E402
from project_state import (  # noqa: E402
    PHASE_ASSEMBLY,
    PHASE_BLOCKED,
    PHASE_COMPLETE,
    PHASE_OUTLINE,
    PHASE_SAMPLE,
    PHASE_SLIDE_GENERATION,
    PHASE_STYLE,
    PHASE_VISUAL_QA,
    SLIDE_ASSEMBLED,
    SLIDE_BLOCKED,
    SLIDE_GENERATED,
    SLIDE_GENERATING,
    SLIDE_GENERATION_FAILED,
    SLIDE_PLANNED,
    SLIDE_QA_FAILED,
    SLIDE_QA_PASSED,
    SLIDE_READY,
    ProjectState,
)

from helpers.fake_assembly import FakeAssembly  # noqa: E402
from helpers.fake_image_worker import (  # noqa: E402
    FakeImageWorker,
    FakeWorkerInterrupted,
    SlidePlan,
    digest_tree,
    is_valid_png,
)

DEFAULT_SLIDES = ("slide_01", "slide_02", "slide_03", "slide_04")

# Slide states AGY may (re)dispatch from. Anything else is either in flight,
# already done, or explicitly blocked and needs an AGY decision first.
DISPATCHABLE_STATES = frozenset({SLIDE_PLANNED, SLIDE_READY, SLIDE_GENERATION_FAILED, SLIDE_QA_FAILED})
# Slide states that must never be re-generated by a resume.
SETTLED_STATES = frozenset({SLIDE_GENERATED, SLIDE_QA_PASSED, SLIDE_ASSEMBLED})

# Phases in which slide generation work may be dispatched at all.
GENERATION_PHASES = frozenset({PHASE_SLIDE_GENERATION, PHASE_VISUAL_QA})


class ExternalProcessSpawned(AssertionError):
    """A recovery test tried to spawn a real process (forbidden in Phase 9)."""


def plan_dispatch(state: ProjectState) -> list[str]:
    """Deterministic resume planner (harness-side, AGY's view).

    Returns the slides a resume is allowed to dispatch, in slide order. It never
    includes a settled slide (``generated`` / ``qa_passed`` / ``assembled``), a
    slide in flight (``generating``), or a ``blocked`` slide, and returns nothing
    at all outside the generation phases -- so resuming a finished project
    dispatches no worker call.
    """
    if state.phase not in GENERATION_PHASES:
        return []
    return [
        slide_id
        for slide_id, slide in sorted(state.data["slides"].items())
        if slide.get("status") in DISPATCHABLE_STATES
    ]


@dataclass
class DispatchOutcome:
    slide_id: str
    generation: int
    result: dict[str, Any] | None
    attempt: dict[str, Any] | None
    interrupted: bool = False

    @property
    def status(self) -> str | None:
        return None if self.result is None else self.result.get("status")

    @property
    def error_code(self) -> str | None:
        return None if self.result is None else self.result.get("error_code")


class RecoveryTestCase(unittest.TestCase):
    """Base class: temp workspace + real ProjectState + fake worker + guards."""

    slide_ids: tuple[str, ...] = DEFAULT_SLIDES
    project_id: str = "ppt_recovery"

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.ws = Path(self._tmp.name) / "deck"
        self.ws.mkdir(parents=True)
        self._install_process_guard()
        self.worker = FakeImageWorker(self.ws)
        self.state = ProjectState.initialize(self.ws, self.project_id, slide_ids=self.slide_ids)
        self.state.save()

    def tearDown(self) -> None:
        self._tmp.cleanup()

    # -- quota / isolation guard -------------------------------------------
    def _install_process_guard(self) -> None:
        def _forbidden(*args: Any, **kwargs: Any):
            raise ExternalProcessSpawned(
                "recovery tests must not spawn a process (no Codex, Kiro or image_gen calls)"
            )

        for target in ("Popen", "run", "call", "check_call", "check_output"):
            patcher = mock.patch.object(subprocess, target, _forbidden)
            patcher.start()
            self.addCleanup(patcher.stop)

    # -- phase driving (AGY) ----------------------------------------------
    def advance_to_slide_generation(self) -> None:
        for gate in ("outline", "style", "sample"):
            self.state.set_gate(gate, "approved")
        for phase in (PHASE_OUTLINE, PHASE_STYLE, PHASE_SAMPLE, PHASE_SLIDE_GENERATION):
            self.state.set_phase(phase)
        self.state.save()

    def reload(self) -> ProjectState:
        """Drop the in-memory object and re-read the state from disk."""
        self.state = ProjectState.load(self.ws)
        return self.state

    # -- slide driving (AGY) ----------------------------------------------
    def mark_ready(self, slide_id: str) -> None:
        slide = self.state.slide(slide_id)
        if slide["status"] != SLIDE_READY:
            self.state.set_slide_status(slide_id, SLIDE_READY)

    def dispatch(
        self,
        slide_id: str,
        operation: str = "generate",
        idempotency_key: str | None = None,
        worker: FakeImageWorker | None = None,
    ) -> DispatchOutcome:
        """One full AGY dispatch: ready -> generating -> record worker result.

        The state is persisted *before* the worker turn (so an interrupted turn
        leaves ``generating`` on disk, exactly like a real crash) and again after
        the result is recorded.
        """
        worker = worker or self.worker
        self.mark_ready(slide_id)
        generation = self.state.begin_generation(slide_id, job_path=f"prompts/{slide_id}.json")
        self.state.save()
        try:
            result = worker.run(slide_id, generation=generation, operation=operation)
        except FakeWorkerInterrupted:
            # No result reaches AGY: the slide stays 'generating' on disk.
            return DispatchOutcome(slide_id, generation, None, None, interrupted=True)
        attempt = self.state.record_worker_result(
            slide_id, result, idempotency_key=idempotency_key
        )
        self.state.save()
        return DispatchOutcome(slide_id, generation, result, attempt)

    def dispatch_all(self, slide_ids: Iterable[str] | None = None) -> list[DispatchOutcome]:
        return [self.dispatch(sid) for sid in (slide_ids or self.slide_ids)]

    def retry(self, slide_id: str) -> None:
        """AGY decision: generation_failed / qa_failed -> ready."""
        self.state.set_slide_status(slide_id, SLIDE_READY)
        self.state.save()

    def qa_pass(self, slide_id: str) -> None:
        self.state.set_slide_status(slide_id, SLIDE_QA_PASSED, by=ps.CONTROLLER)
        self.state.save()

    def qa_fail(self, slide_id: str) -> None:
        self.state.set_slide_status(slide_id, SLIDE_QA_FAILED, by=ps.CONTROLLER)
        self.state.save()

    def block_slide(self, slide_id: str) -> None:
        self.state.set_slide_status(slide_id, SLIDE_BLOCKED)
        self.state.save()

    def block_project(self, note: str | None = None) -> None:
        self.state.set_phase(PHASE_BLOCKED, note=note)
        self.state.save()

    # -- crash simulation --------------------------------------------------
    def simulate_crash_while_generating(self, slide_id: str) -> int:
        """Leave ``slide_id`` in ``generating`` on disk with no recorded result."""
        self.mark_ready(slide_id)
        generation = self.state.begin_generation(slide_id, job_path=f"prompts/{slide_id}.json")
        self.state.save()
        return generation

    def simulate_crash_after_completed_result(
        self, slide_id: str, keep_artifact: bool = True
    ) -> int:
        """Crash *after* a completed result + artifact, before the status write.

        Produces the only state from which recovery may deterministically
        conclude success: a recorded ``completed`` attempt for the in-flight
        generation plus a verified artifact on disk.
        """
        outcome = self.dispatch(slide_id)
        assert outcome.status == "completed", "plan must succeed for this crash shape"
        slide = self.state.slide(slide_id)
        slide["status"] = SLIDE_GENERATING
        slide["generating_attempt"] = outcome.generation
        self.state.save()
        if not keep_artifact:
            artifact = self.ws / slide["image_path"]
            artifact.unlink()
        return outcome.generation

    # -- assembly ----------------------------------------------------------
    def new_assembly(self, fail_times: int = 0, **kwargs: Any) -> FakeAssembly:
        return FakeAssembly(self.ws, fail_times=fail_times, **kwargs)

    def image_digests(self) -> dict[str, str]:
        return digest_tree(self.ws)

    # -- assertions --------------------------------------------------------
    def assert_slide(self, slide_id: str, status: str, generation: int | None = None,
                     attempts: int | None = None) -> dict[str, Any]:
        slide = self.state.slide(slide_id)
        self.assertEqual(slide["status"], status, f"{slide_id} status")
        if generation is not None:
            self.assertEqual(slide["generation"], generation, f"{slide_id} generation")
        if attempts is not None:
            self.assertEqual(len(slide["attempts"]), attempts, f"{slide_id} attempts")
        return slide

    def assert_not_generated(self, slide_id: str) -> dict[str, Any]:
        """The slide never reached a success state and holds no final image."""
        slide = self.state.slide(slide_id)
        self.assertNotIn(slide["status"], SETTLED_STATES, f"{slide_id} must not be settled")
        image_path = slide.get("image_path")
        if image_path is not None:
            self.assertFalse(
                (self.ws / image_path).exists(),
                f"{slide_id} recorded image_path {image_path!r} that must not be a final output",
            )
        return slide

    def assert_valid_final_image(self, slide_id: str) -> Path:
        slide = self.state.slide(slide_id)
        image_path = slide.get("image_path")
        self.assertIsNotNone(image_path, f"{slide_id} has no image_path")
        resolved = self.ws / image_path
        self.assertTrue(is_valid_png(resolved), f"{slide_id} image is not a valid raster image")
        return resolved

    def assert_untouched(self, slide_ids: Iterable[str], expected: dict[str, dict[str, Any]]) -> None:
        """Assert status/generation/attempt count are unchanged for slides."""
        for slide_id in slide_ids:
            slide = self.state.slide(slide_id)
            want = expected[slide_id]
            self.assertEqual(slide["status"], want["status"], f"{slide_id} status changed")
            self.assertEqual(
                slide["generation"], want["generation"], f"{slide_id} generation changed"
            )
            self.assertEqual(
                len(slide["attempts"]), want["attempts"], f"{slide_id} attempt history changed"
            )

    def snapshot(self, slide_ids: Iterable[str] | None = None) -> dict[str, dict[str, Any]]:
        return {
            slide_id: {
                "status": self.state.slide(slide_id)["status"],
                "generation": self.state.slide(slide_id)["generation"],
                "attempts": len(self.state.slide(slide_id)["attempts"]),
            }
            for slide_id in (slide_ids or self.slide_ids)
        }
